# .github/workflows/localize-images.yml
name: Localize External Images

on:
  workflow_dispatch: 

jobs:
  localize-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create blog-content-img base directory
        run: |
          mkdir -p public/blog-content-img

      - name: Install dependencies
        run: |
          npm init -y
          npm install axios crypto

      - name: Run image localization
        run: node localize-images.js

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Localize external images in blog posts

          - Downloaded external images to public/blog-content-img/
          - Updated markdown files to use local image paths
          - Automated by GitHub Actions"
          git push

      - name: Create summary
        run: |
          echo "## Image Localization Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
            echo "**Changes detected and committed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "External images have been downloaded and markdown files updated." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Changed files:" >> $GITHUB_STEP_SUMMARY
            git diff --name-only HEAD~1 HEAD | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          else
            echo "**No changes needed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "All images are already localized or no external images found." >> $GITHUB_STEP_SUMMARY
          fi